version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Starting Flask app..."
      - nohup python app

artifacts:
  files:
    - notes.py
    - templates/index.html
    - note.txt
